version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4.13
    restart: always
    networks:
      - disconf
  redis:
    container_name: redis
    image: redis
    restart: always
    command: redis-server --appendonly yes --requirepass "123456"
    volumes:
      - ./data/redis:/data
    networks:
      - disconf
  mysql:
    container_name: mysql
    image: mysql:5.7.25
    restart: always
    ports:
      - 3306:3306
    environment:
       - MYSQL_ROOT_PASSWORD=123456
       - MYSQL_USER=green
       - MYSQL_PASSWORD=123456
       - MYSQL_DATABASE=disconf
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./data/mysql/:/var/lib/mysql
    networks:
      - disconf
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./web/war/html:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - disconf
  disconfApi:
    container_name: disconf
    image: tomcat:8.5.37-jre8-alpine
    restart: always
    volumes:
      - ./web/war:/usr/local/tomcat/webapps/ROOT
    networks:
      - disconf
networks:
  disconf:
